### ISSUE TITLE
LMS Build error - top level await

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#211]
`packages/lms/src/lib/stores/courseProgress.ts:39`

```ts
export const progressMapStore = await localStorageProgressMapStore('contentCompletionMap');
```

```basherror during build:
Error: Transform failed with 2 errors:
_app/immutable/chunks/courseProgress.!~{01M}~.js:506:26: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
_app/immutable/chunks/courseProgress.!~{01M}~.js:535:25: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
    at failureErrorWithLog (/Users/oliver/Repos/Noroff/Content/-mollify/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/oliver/Repos/Noroff/Content/-mollify/node_modules/esbuild/lib/main.js:837:29
    at responseCallbacks.<computed> (/Users/oliver/Repos/Noroff/Content/-mollify/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/oliver/Repos/Noroff/Content/-mollify/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/oliver/Repos/Noroff/Content/-mollify/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by Fermain** [comment]
https://github.com/Fermain/-mollify/blob/152913cf3cda483c3241bf73a7391d09c53daefe/packages/lms/src/lib/stores/courseRelationMap.ts#L12C1-L13C1

**Comment by Fermain** [comment]
I think these stores are causing the issue, I think that they can be made synchronous with some changes
